### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by thuydx55** [Busta117/SQLiteUnityKit#1]
This repo is good for us for connecting to sqlite database. But how can we connect to an encryption sqlite database with password

**Comment by Busta117** [comment]
hi, the encryption option of the sqlite is not a basic functionality of sqlite, so, the basic libs of sqlite does not support encryption, this framework use the basic sqlite libs

**Comment by thuydx55** [comment]
thanks, so there are no way to encrypt database, isn't it?. It's very easy to modify database while game is running on devices

**Comment by Busta117** [comment]
depends of the device, in iOS is possible modify the database only if your device is jailbroken, but always you can encrypt the fields of the database, maybe do some md5, or append control characters or something like that to prevent the easy modification, more than encrypt the database file, encrypt the fields on the database

this is my advice.
